wso2/carbon-business-process

components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/engine/runtime/xpath/JaxpFunctionResolver.java, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/engine/runtime/xpath/XPath2Constants.java
Implementation for the remaining XpathFunctions in the JaxpFunctionResolver according to the Humantask spec. Added required constants in the XPath2Constants.
=> Implementation  for missing HumanTask xpath functions

components/humantask/humantask-explorer-web/src/web/controller/completeActionController.jag, components/humantask/humantask-explorer-web/src/web/controller/inboxTaskController.jag, components/humantask/humantask-explorer-web/src/web/controller/saveActionController.jag, components/humantask/humantask-explorer-web/src/web/jaggery.conf, components/humantask/humantask-explorer-web/src/web/js/WSHTRequest.js, components/humantask/humantask-explorer-web/src/web/js/actions.js, components/humantask/humantask-explorer-web/src/web/model/common.jag, components/humantask/humantask-explorer-web/src/web/model/taskModel.jag, components/humantask/humantask-explorer-web/src/web/template/inboxTaskView.jag, components/humantask/humantask-explorer-web/src/web/template/modals/verifyTaskCompletion.jag, components/humantask/org.wso2.carbon.humantask/pom.xml, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/api/rendering/HTRenderingApiImpl.java, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/api/rendering/NamespaceResolver.java, components/humantask/org.wso2.carbon.humantask/src/main/resources/META-INF/HumanTaskRenderingAPI.wsdl, components/humantask/org.wso2.carbon.humantask/src/main/resources/META-INF/services.xml, features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml, pom.xml, service-stubs/humantask/org.wso2.carbon.humantask.skeleton/pom.xml, service-stubs/humantask/org.wso2.carbon.humantask.skeleton/src/main/resources/ws-humantask-rendering-api.wsdl, service-stubs/humantask/org.wso2.carbon.humantask.stub/pom.xml, service-stubs/humantask/org.wso2.carbon.humantask.stub/src/main/resources/ws-humantask-rendering-api.wsdl
Add HTRenderingAPI adminservice and rendering support in humantask explorer
=> Adding HT Form Rendering support

components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/api/rendering/HTRenderingApiImpl.java, components/humantask/org.wso2.carbon.humantask/src/main/resources/META-INF/HumanTaskRenderingAPI.wsdl, service-stubs/humantask/org.wso2.carbon.humantask.skeleton/src/main/resources/ws-humantask-rendering-api.wsdl, service-stubs/humantask/org.wso2.carbon.humantask.stub/src/main/resources/ws-humantask-rendering-api.wsdl
fix for https://wso2.org/jira/browse/BPS-653
=> https://wso2.org/jira/browse/BPS-653

components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/store/HumanTaskStore.java
Adding the transports to axis2 service by reading from the tenant transport config for issue - https://wso2.org/jira/browse/BPS-601
=> Adding axis2 transports via tenant transport config

components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/BPELSchedulerShutdown.java, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/engine/runtime/xpath/JaxpFunctionResolver.java
Adding findBug bug fixes for JaxpFunctionResolver and BPELSchedulerShutdown.
=> FindBug bug fixes for JaxpFunctionResolver and BPELSchedulerShutdown

components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/web/bpel/list_instances.jsp
Encoding advance filter parameters before sending to avoid removing '+' . For issue - https://wso2.org/jira/browse/BPS-460
=> Fixing advanced filter issue

components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/store/HumanTaskStore.java
Removing humantask depoloyment directory, if the deployment failed,for issue-https://wso2.org/jira/browse/BPS-617
=> Removing humantask deployment directory, if the deployment failed

components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/BPELBindingContextImpl.java, components/unified-endpoint/org.wso2.carbon.unifiedendpoint.core/src/main/java/org/wso2/carbon/unifiedendpoint/core/UnifiedEndpointFactory.java
Throwing a deployment exception when the epr file not found in BPEL deployment. fix for issue - https://wso2.org/jira/browse/BPS-530
=> Fix for NPE thrown when epr not available for BPEL

components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/org/wso2/carbon/bpel/ui/i18n/Resources.properties, components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/web/bpel/process_list.jsp, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/BPELConstants.java, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/mgt/services/BPELPackageManagementServiceSkeleton.java, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/store/BPELUIException.java, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/store/TenantProcessStoreImpl.java, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/store/TooMuchInstancesException.java, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/store/Utils.java, components/bpel/org.wso2.carbon.bpel/src/main/resources/META-INF/bps_management.xsd, components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xml, components/bpel/org.wso2.carbon.bpel/src/test/resources/conf/bps.xml, features/bpel/org.wso2.carbon.bpel.server.feature/resources/conf/bps.xml, service-stubs/bpel/org.wso2.carbon.bpel.skeleton/src/main/resources/bps_management.xsd, service-stubs/bpel/org.wso2.carbon.bpel.stub/src/main/resources/bps_management.xsd
Aborting undeploy if there are too much instances. Issue - https://wso2.org/jira/browse/BPS-363
=> Aborting undeploy if there are instances more than the limit

components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/web/bpel/js/bpel-main.js, components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/web/bpel/process_info.jsp
Fixing layout issues in process info view for issue - https://wso2.org/jira/browse/BPS-684
=> Fixing layout issues in process info view

components/humantask/humantask-explorer-web/src/web/controller/inboxTaskController.jag, components/humantask/humantask-explorer-web/src/web/model/taskModel.jag, components/humantask/humantask-explorer-web/src/web/template/partials/internalError.jag, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/api/client/TaskOperationsImpl.java, service-stubs/humantask/org.wso2.carbon.humantask.skeleton/src/main/resources/ws-humantask-api.wsdl
Adding authorisation in the backend and visual feedback on error in ht web app for loadTask() operation. Issue - https://wso2.org/jira/browse/BPS-680
=> Unauthorized error message is not showing for Excluded owner in HumanTask web app

components/humantask/humantask-explorer-web/src/web/controller/actionController.jag, components/humantask/humantask-explorer-web/src/web/js/WSHTRequest.js, components/humantask/humantask-explorer-web/src/web/js/actions.js, components/humantask/humantask-explorer-web/src/web/model/taskModel.jag, components/humantask/humantask-explorer-web/src/web/template/inboxTaskView.jag
Adding Skip action in HT-Explorer for Issue - https://wso2.org/jira/browse/BPS-679
=> Adding Skip action in HT-Explorer

components/bpmn/bpmn-explorer-web/src/web/css/style.css, components/bpmn/bpmn-explorer-web/src/web/template/inboxTaskView.jag, components/bpmn/bpmn-explorer-web/src/web/template/partials/navigation.jag, components/bpmn/bpmn-explorer-web/src/web/template/statsView.jag, components/humantask/humantask-explorer-web/src/web/css/style.css, components/humantask/humantask-explorer-web/src/web/template/allTasksPoolView.jag, components/humantask/humantask-explorer-web/src/web/template/inboxTaskView.jag, components/humantask/humantask-explorer-web/src/web/template/modals/addCommentModal.jag, components/humantask/humantask-explorer-web/src/web/template/modals/assignTaskModal.jag, components/humantask/humantask-explorer-web/src/web/template/modals/attachmentUploadModal.jag, components/humantask/humantask-explorer-web/src/web/template/modals/setPriorityModal.jag, components/humantask/humantask-explorer-web/src/web/template/modals/verifyTaskCompletion.jag
Fixed,
Tab hover effect should be consistent over both apps.
BPMN dashboard chart titles should be changed.
Resize form buttons.
Fix pagination button colours.
Change Button types to be consistent over the app.
Change Tab names
=> Jaggery apps, theme fixes. Issue - https://wso2.org/jira/browse/BPS-711

components/humantask/humantask-explorer-web/src/web/template/inboxTaskView.jag
Fixing issue - https://wso2.org/jira/browse/BPS-707
=> Fixing HT summary view when there is no owner

components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/BPELConstants.java
changing analytics namespace. Issue - https://wso2.org/jira/browse/BPS-698
=> changing analytics namespace

components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/BPELServerImpl.java, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/config/BPELServerConfiguration.java, components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xml, components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xsd, components/bpel/org.wso2.carbon.bpel/src/test/resources/conf/bps.xml, features/bpel/org.wso2.carbon.bpel.server.feature/resources/conf/bps.xml
Adding transaction manager timeout configurations for issue - https://wso2.org/jira/browse/BPS-596
=> Adding transaction manager timeout configurations

components/attachment-mgt/org.wso2.carbon.attachment.mgt/src/main/java/org/wso2/carbon/attachment/mgt/api/Resource.java, components/attachment-mgt/org.wso2.carbon.attachment.mgt/src/main/java/org/wso2/carbon/attachment/mgt/client/dto2api/TransformerUtil.java, components/attachment-mgt/org.wso2.carbon.attachment.mgt/src/main/java/org/wso2/carbon/attachment/mgt/core/AttachmentImpl.java, components/attachment-mgt/org.wso2.carbon.attachment.mgt/src/main/java/org/wso2/carbon/attachment/mgt/core/ResourceImpl.java, components/attachment-mgt/org.wso2.carbon.attachment.mgt/src/main/java/org/wso2/carbon/attachment/mgt/core/dao/impl/jpa/openjpa/AttachmentMgtDAOFactoryImpl.java, components/humantask/humantask-explorer-web/src/web/controller/authenticator.jag, components/humantask/humantask-explorer-web/src/web/jaggery.conf, components/humantask/humantask-explorer-web/src/web/js/actions.js, components/humantask/org.wso2.carbon.humantask.ui/src/main/java/org/wso2/carbon/humantask/ui/fileupload/AttachmentUploadClient.java, components/humantask/org.wso2.carbon.humantask.ui/src/main/java/org/wso2/carbon/humantask/ui/fileupload/AttachmentUploadExecutor.java
fixing attachmant download support for HT explorer. https://wso2.org/jira/browse/BPS-712
Fixing dummy username and default date in attachment upload component. Issue - https://wso2.org/jira/browse/BPS-731
=> Attachment support

components/humantask/humantask-explorer-web/src/web/controller/loginController.jag
https://wso2.org/jira/browse/BPS-752
=> Fix: https://wso2.org/jira/browse/BPS-752

components/bpmn/bpmn-explorer-web/src/web/model/claimableTaskModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/common.jag, components/bpmn/bpmn-explorer-web/src/web/model/historicTasksModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/myTasksModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/processModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/statsModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/partials/navigation.jag, components/humantask/humantask-explorer-web/src/web/model/allTasksModel.jag, components/humantask/humantask-explorer-web/src/web/model/common.jag, components/humantask/humantask-explorer-web/src/web/model/myTasksModel.jag, components/humantask/humantask-explorer-web/src/web/model/notificationListModel.jag, components/humantask/humantask-explorer-web/src/web/model/taskPoolModel.jag, components/humantask/humantask-explorer-web/src/web/template/partials/navigation.jag
Fix for https://wso2.org/jira/browse/BPS-749
=> Fix for https://wso2.org/jira/browse/BPS-749

components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/template/taskView.jag
Fix: https://wso2.org/jira/browse/BPS-759
=> Fix: https://wso2.org/jira/browse/BPS-759

components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/template/taskView.jag
Fix: https://wso2.org/jira/browse/BPS-756
=> Fix: https://wso2.org/jira/browse/BPS-756

components/humantask/humantask-explorer-web/src/web/controller/authenticator.jag, components/humantask/humantask-explorer-web/src/web/model/searchModel.jag
ERROR {JAGGERY.controller.authenticator:jag} -  org.mozilla.javascript.EcmaError: TypeError: Cannot call method "toString" of null (/humantask-explorer/controller/authenticator.jag#133)
=> [humantask-explorer] fix error displayed when debug enabled 

components/bpmn/bpmn-explorer-web/src/web/controller/searchController.jag, components/bpmn/bpmn-explorer-web/src/web/jaggery.conf, components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/model/common.jag, components/bpmn/bpmn-explorer-web/src/web/model/searchModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/partials/navigation.jag, components/bpmn/bpmn-explorer-web/src/web/template/searchView.jag
https://wso2.org/jira/browse/BPS-764
=> Add advance search https://wso2.org/jira/browse/BPS-764

components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/model/searchModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/taskModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/searchView.jag
Add functionality to search completed tasks to https://wso2.org/jira/browse/BPS-764
=> Add functionality to search completed tasks

components/humantask/humantask-explorer-web/src/web/template/taskInstanceView.jag
Adding human task view UI bug fixes. Issue - https://wso2.org/jira/browse/BPS-778
=> Adding human task view UI bug fixes.

components/humantask/humantask-explorer-web/src/web/template/claimableTasksView.jag, components/humantask/humantask-explorer-web/src/web/template/notificationListView.jag
Changing Ht-explorer incorrect page titles.  https://wso2.org/jira/browse/BPS-785
=> Changing Ht-explorer incorrect page titles. 

components/humantask/humantask-explorer-web/src/web/template/myTasksView.jag
Adding OBSOLETE status filter in Ht-explorer myTask page. Issue - https://wso2.org/jira/browse/BPS-781
=> Adding OBSOLETE status filter in Ht-explorer myTask page. 

components/humantask/humantask-explorer-web/src/web/js/actions.js, components/humantask/humantask-explorer-web/src/web/model/common.jag, components/humantask/humantask-explorer-web/src/web/template/taskInstanceView.jag
Issue - https://wso2.org/jira/browse/BPS-780
=> adding date formatings to task view.

components/bpmn/bpmn-explorer-web/src/web/controller/statsController.jag, components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/model/statsModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/statsView.jag
=> Bpmn explorer

components/bpmn/bpmn-explorer-web/src/web/model/startProcessModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/processView.jag
Display error message when process start
=> Fix https://wso2.org/jira/browse/BPS-784

components/bpmn/bpmn-explorer-web/src/web/model/claimModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/claimableTaskModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/common.jag, components/bpmn/bpmn-explorer-web/src/web/model/completedTaskModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/historicTasksModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/myTasksModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/processModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/searchModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/taskModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/claimTaskView.jag, components/bpmn/bpmn-explorer-web/src/web/template/claimableTaskView.jag, components/bpmn/bpmn-explorer-web/src/web/template/completedTaskView.jag, components/bpmn/bpmn-explorer-web/src/web/template/historicTasksView.jag, components/bpmn/bpmn-explorer-web/src/web/template/myTasksView.jag, components/bpmn/bpmn-explorer-web/src/web/template/processView.jag, components/bpmn/bpmn-explorer-web/src/web/template/searchView.jag, components/bpmn/bpmn-explorer-web/src/web/template/startProcessView.jag, components/bpmn/bpmn-explorer-web/src/web/template/taskView.jag
Add functionality to display error messages returned by REST API
=> Complete fix for https://wso2.org/jira/browse/BPS-784

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/META-INF/component.xml
https://wso2.org/jira/browse/BPS-776
=> Change component name to BPMN Data Publisher in menu item list

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/instance_list_view.jsp
Issue - https://wso2.org/jira/browse/BPS-800
=> Avoiding NPE when process has no name in BPMN instance view.

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/instance_list_view.jsp
Issue - https://wso2.org/jira/browse/BPS-795
=> Fixing redirection to process view after clicking delete all in bpmn ui.

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/instance_variables.jsp
fixed in https://wso2.org/jira/browse/BPS-777
=> Sort BPEL and BPMN instance variables by name in instance view

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/java/org/wso2/carbon/bpmn/ui/WorkflowServiceClient.java, components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/instance_list_view.jsp
fix for instance advanced search in management console
=> fix: https://wso2.org/jira/browse/BPS-793 for management console

components/bpmn/bpmn-explorer-web/src/web/template/processView.jag, components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/org/wso2/carbon/bpmn/ui/i18n/Resources.properties, components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/process_definition.jsp
https://wso2.org/jira/browse/BPS-783
=> Display a proper message if BPMNDiagram element is not present in a BPMN model

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/instance_variables.jsp
Issue - https://wso2.org/jira/browse/BPS-791
=> Showing process diagram in bpmn completed instances.

components/humantask/humantask-explorer-web/src/web/template/taskInstanceView.jag
Issue - https://wso2.org/jira/browse/BPS-804
=> removing complete and save buttons when no rendering. 

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/process_list_view.jsp
Issue -https://wso2.org/jira/browse/BPS-808
=> Removing search fields when no bpmn processes. 

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/META-INF/component.xml, components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/org/wso2/carbon/bpmn/ui/i18n/Resources.properties, components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/process_list_view.jsp, components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/upload_bpmn.jsp
fix bpmn package managemnt and process view
=> fix : https://wso2.org/jira/browse/BPS-803 

components/bpel/org.wso2.carbon.bpel.ui/src/main/java/org/wso2/carbon/bpel/ui/BpelUIUtil.java, components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/web/bpel/process_list.jsp
fixed https://wso2.org/jira/browse/BPS-787
=> Fixed issue with processcleanup.sh tool

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/process_list_view.jsp
Issue - https://wso2.org/jira/browse/BPS-816
=> Removing time string from bpmn process list, date column since api does not send a time

components/humantask/humantask-explorer-web/src/web/README.md, components/humantask/humantask-explorer-web/src/web/config/config.json, components/humantask/humantask-explorer-web/src/web/controller/authenticator.jag, components/humantask/humantask-explorer-web/src/web/controller/completeActionController.jag, components/humantask/humantask-explorer-web/src/web/controller/saveActionController.jag, components/humantask/humantask-explorer-web/src/web/js/actions.js, components/humantask/humantask-explorer-web/src/web/model/common.jag, components/humantask/humantask-explorer-web/src/web/template/partials/header.jag
Add tenant support for humantask-explorer
=> Fix: https://wso2.org/jira/browse/BPS-820

components/humantask/humantask-explorer-web/src/web/template/statsView.jag
Fixed with: https://github.com/wso2/carbon-business-process/pull/173
=> Updated statsView for the human-task explorer 

components/bpmn/bpmn-explorer-web/src/web/config/config.json, components/bpmn/bpmn-explorer-web/src/web/controller/reportController.jag, components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/model/claimableTaskModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/common.jag, components/bpmn/bpmn-explorer-web/src/web/model/historicTasksModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/myTasksModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/processModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/reportModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/searchModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/statsModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/partials/header.jag, components/bpmn/bpmn-explorer-web/src/web/template/processView.jag, components/bpmn/bpmn-explorer-web/src/web/template/reportView.jag, components/bpmn/bpmn-explorer-web/src/web/template/taskView.jag
provide tenant support for bpmn-explorer
=> https://wso2.org/jira/browse/BPS-821

components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/org/wso2/carbon/bpmn/ui/i18n/Resources.properties, components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/process_list_view.jsp
Jira: https://wso2.org/jira/browse/BPS-838
=> BPMN process list view doesn't show the data table when there are no processes

components/humantask/humantask-explorer-web/src/web/controller/actionController.jag, components/humantask/humantask-explorer-web/src/web/js/WSHTRequest.js, components/humantask/humantask-explorer-web/src/web/js/actions.js, components/humantask/humantask-explorer-web/src/web/template/notificationView.jag, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/api/client/TransformerUtils.java, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/engine/util/OperationAuthorizationUtil.java
Issue - https://wso2.org/jira/browse/BPS-891
=> Adding missing authorizations for notifications remove operation and remove button in ht-explorer

components/bpmn/bpmn-explorer-web/src/web/template/taskView.jag
Jira - https://wso2.org/jira/browse/BPS-882
=> Removing Complete button from BPMN SUSPENDED task view.

components/bpmn/bpmn-explorer-web/src/web/model/claimableTaskModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/common.jag
Jira - https://wso2.org/jira/browse/BPS-880
=> Passing tenant username without domain part to retrieve claimable tasks in bpmn

components/bpmn/bpmn-explorer-web/src/web/model/completedTaskModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/completedTaskView.jag
jira - https://wso2.org/jira/browse/BPS-886
=> adding attachments list to bpmn completed task view.

components/humantask/humantask-explorer-web/src/web/template/taskInstanceView.jag, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/api/rendering/HTRenderingApiImpl.java, components/humantask/org.wso2.carbon.humantask/src/main/resources/META-INF/HumanTaskRenderingAPI.wsdl, service-stubs/humantask/org.wso2.carbon.humantask.skeleton/src/main/resources/ws-humantask-rendering-api.wsdl
Jira - https://wso2.org/jira/browse/BPS-901
=> Adding read only attribute for HT renderings.

components/bpmn/bpmn-explorer-web/src/web/css/style.css, components/bpmn/bpmn-explorer-web/src/web/template/statsView.jag
Issue-https://wso2.org/jira/browse/BPS-765
=> adding pagination to BPMN instance chart.

components/bpmn/bpmn-explorer-web/src/web/js/actions.js
Issue - https://wso2.org/jira/browse/BPS-911
=> adding error message upon bpmn task completion. 

components/bpmn/bpmn-explorer-web/src/web/css/style.css, components/bpmn/bpmn-explorer-web/src/web/template/statsView.jag
Issue - https://wso2.org/jira/browse/BPS-765
=> BPMN dashboard pagination page counts. 

components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/common/RestResponseFactory.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/common/utils/BPMNOSGIService.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/common/utils/DateToStringSerializer.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/common/utils/Utils.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/common/DataResponse.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/identity/GroupPaginateList.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/identity/GroupResponse.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/identity/UserInfoRequest.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/identity/UserInfoResponse.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/identity/UserPaginateList.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/identity/UserResponse.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/runtime/JobPaginateList.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/runtime/JobResponse.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/runtime/ProcessEngineInfoResponse.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/model/runtime/TableResponse.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/service/base/BaseIdentityService.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/service/base/BaseRuntimeService.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/service/identity/IdentityService.java, components/bpmn/bpmn-rest/src/main/java/org/wso2/carbon/bpmn/rest/service/management/ManagementService.java, components/bpmn/bpmn-rest/src/main/webapp/WEB-INF/beans.xml, components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/integration/BPSUserIdentityManager.java
Issue - https://wso2.org/jira/browse/BPS-925
=> BPMN REST API management and identity components. 

components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/common/utils/Utils.java, components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/base/BaseExecutionService.java, components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/ExecutionService.java, components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/ProcessInstanceService.java, components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/WorkflowTaskService.java
=> Fix: https://wso2.org/jira/browse/BPS-1018 and https://wso2.org/jira/browse/BPS-1022

components/bpmn/bpmn-explorer-web/src/web/config/locales/locale_en.json, components/bpmn/bpmn-explorer-web/src/web/controller/substitutionsController.jag, components/bpmn/bpmn-explorer-web/src/web/css/style.css, components/bpmn/bpmn-explorer-web/src/web/jaggery.conf, components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/model/common.jag, components/bpmn/bpmn-explorer-web/src/web/model/substitutionsModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/partials/navigation.jag, components/bpmn/bpmn-explorer-web/src/web/template/substitutionsView.jag
Feature Add : https://wso2.org/jira/browse/BPS-1031
Add a UI allowing to change a user's substitute, from, to and enabled info.
=> Feature Add : https://wso2.org/jira/browse/BPS-1031

components/bpmn/bpmn-explorer-web/src/web/config/locales/locale_en.json, components/bpmn/bpmn-explorer-web/src/web/controller/adminSubstitutionsController.jag, components/bpmn/bpmn-explorer-web/src/web/jaggery.conf, components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/model/adminSubstitutionsModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/adminSubstitutionsView.jag, components/bpmn/bpmn-explorer-web/src/web/template/modals/addSubstituteModal.jag, components/bpmn/bpmn-explorer-web/src/web/template/modals/updateSubstituteModal.jag, components/bpmn/bpmn-explorer-web/src/web/template/partials/navigation.jag, components/bpmn/bpmn-explorer-web/src/web/template/substitutionsView.jag, components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/UserSubstitutionService.java
Add admin substitution View and common modals
=> Feature: https://wso2.org/jira/browse/BPS-1031

components/bpmn/bpmn-explorer-web/src/web/assets/authentication.js, components/bpmn/bpmn-explorer-web/src/web/config/locales/locale_en.json, components/bpmn/bpmn-explorer-web/src/web/controller/adminSubstitutionsController.jag, components/bpmn/bpmn-explorer-web/src/web/controller/authenticator.jag, components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/model/adminSubstitutionsModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/common.jag, components/bpmn/bpmn-explorer-web/src/web/model/substitutionsModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/adminSubstitutionsView.jag, components/bpmn/bpmn-explorer-web/src/web/template/partials/header.jag, components/bpmn/bpmn-explorer-web/src/web/template/substitutionsView.jag, components/bpmn/bpmn-explorer-web/src/web/template/unauthorizedView.jag
Add: User input validation, unauth view, and some improvements for Feature: https://wso2.org/jira/browse/BPS-1031 and fix csrf.js not found issue
=> Additions for Feature : https://wso2.org/jira/browse/BPS-1031

components/bpmn/bpmn-explorer-web/src/web/config/locales/locale_en.json, components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/template/adminSubstitutionsView.jag
Add: substitute update option(in Admin Substitute view) for Feature: https://wso2.org/jira/browse/BPS-1031
=> Add: substitute update option(in Admin Substitute view) for  Feature: https://wso2.org/jira/browse/BPS-1031

components/bpmn/bpmn-explorer-web/src/web/model/adminSubstitutionsModel.jag, components/bpmn/bpmn-explorer-web/src/web/model/common.jag, components/bpmn/bpmn-explorer-web/src/web/model/substitutionsModel.jag, components/bpmn/bpmn-explorer-web/src/web/template/partials/navigation.jag
Add functionality to disable substitution views when user substitution feature is disabled for Feature: https://wso2.org/jira/browse/BPS-1031
=> Add functionality for Feature: https://wso2.org/jira/browse/BPS-1031

components/bpmn/bpmn-explorer-web/src/web/config/locales/locale_en.json, components/bpmn/bpmn-explorer-web/src/web/model/common.jag, components/bpmn/bpmn-explorer-web/src/web/template/adminSubstitutionsView.jag, components/bpmn/bpmn-explorer-web/src/web/template/substitutionsView.jag
Add functionality to return to my substitution view from admin view for Feature:https://wso2.org/jira/browse/BPS-1031
=> Add functionality for Feature:https://wso2.org/jira/browse/BPS-1031

components/bpmn/bpmn-explorer-web/src/web/template/claimableTaskView.jag, components/bpmn/bpmn-explorer-web/src/web/template/historicTasksView.jag, components/bpmn/bpmn-explorer-web/src/web/template/myTasksView.jag, components/bpmn/bpmn-explorer-web/src/web/template/processView.jag, components/bpmn/bpmn-explorer-web/src/web/template/substitutionsView.jag
fix mytasks, claimabletasks, process, completed tasks views
=> [BPMN-Explorer] Fix: https://wso2.org/jira/browse/BPS-1110

components/bpmn/bpmn-explorer-web/src/web/config/locales/locale_en.json, components/bpmn/bpmn-explorer-web/src/web/template/adminSubstitutionsView.jag, components/bpmn/bpmn-explorer-web/src/web/template/advancedFilterView.jag, components/bpmn/bpmn-explorer-web/src/web/template/processMonitoringView.jag
fix adminSubstitutionsView, advancedFilterView, processMonitoringView
=> Fix: https://wso2.org/jira/browse/BPS-1110

components/bpmn/bpmn-explorer-web/src/web/config/locales/locale_en.json, components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/bpmn-explorer-web/src/web/template/taskView.jag
=> Fix: https://wso2.org/jira/browse/BPS-1112

components/bpmn/bpmn-explorer-web/src/web/template/partials/navigation.jag
=> [BPMN-Explorer] Fix: https://wso2.org/jira/browse/BPS-1113

components/humantask/org.wso2.carbon.humantask.ui/src/main/resources/web/humantask/js/humantask.js, components/humantask/org.wso2.carbon.humantask.ui/src/main/resources/web/humantask/task_view_temp.jsp
Making task view read-only to avoid security issues
=> https://wso2.org/jira/browse/BPS-1056. 

components/bpmn/org.wso2.carbon.bpmn.extensions/src/main/java/org/wso2/carbon/bpmn/extensions/rest/RESTInvoker.java, components/bpmn/org.wso2.carbon.bpmn.extensions/src/main/java/org/wso2/carbon/bpmn/extensions/rest/RESTTask.java
https://github.com/wso2/product-ei/issues/774
https://github.com/wso2/product-ei/issues/790
https://github.com/wso2/product-ei/issues/800
https://github.com/wso2/product-ei/issues/801
=> [EI-790][EI-800][EI-801][EI-774] Fix BPMN Rest task bugs

components/bpmn/bpmn-explorer-web/src/web/assets/dynamicFormGen.js, components/bpmn/bpmn-explorer-web/src/web/js/actions.js, components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/ProcessInstanceService.java
This PR contains, 
BPMN explorer form date format support : https://wso2.org/jira/browse/BPS-1162
Fix for BPMN rest API not supporting the Process Initiator variable : https://wso2.org/jira/browse/BPS-1163
=> [BPS-1162][BPS-1163]BPMN parallel user task fixes

features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml, features/bpel/org.wso2.carbon.bpel.ui.feature/pom.xml, features/bpel/pom.xml, pom.xml
=> updating traql version

components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/model/runtime/ProcessDefinitionActionRequest.java, components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/repository/ProcessDefinitionService.java
This will fix https://github.com/wso2/product-ei/issues/1454
This will improve bpmn rest api to support activate and suspend process definitions.
PUT repository/process-definitions/{processDefinitionId}
{
"action" : "suspend",
"includeProcessInstances" : "false",
"date" : "2013-04-15T00:42:12Z"
}
> Brief description of the new feature or bug fix as it will appear in the …
=> Support activate and suspend process definitions

components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/web/bpel/process_list.jsp, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/mgt/services/InstanceManagementServiceSkeleton.java
This fix handles null pointer which occurs when a non existing process instance ID is passed to getInstanceInfo Admin service.
Issue - https://github.com/wso2/product-ei/issues/1558
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” …
=> Fix for https://github.com/wso2/product-ei/issues/1558

pom.xml
This PR updates ode version to 1.3.5-wso2v19 for weekly release
> Link to the PR for changes to the training content in …
=> Update ode version to 1.3.5-wso2v19

components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/types/datatypes/json/api/JsonNodeObject.java
> Fix the NPE as explained in the issue https://github.com/wso2/product-ei/issues/1406.
> Support Null Json values in BPMN REST task.
> When the 'null' is returned as the value of a Json response, it should
be considered same as a primitive value.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in …
=> Handle null json values in BPMN REST task:EI-1406

pom.xml
>Update carbon commons version to the latest for EI update 19 release
=> Update carbon commons version

pom.xml
> Update axis2 and commons versions for the EI Update 20
=> Update axis2 and commons versions

components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/PartnerService.java
Fix https://github.com/wso2/product-ei/issues/1882
Tenant information is added when calling  PartnerService invoke method such that thread invoking the external partner services will have the tenant information
>
> Link to the PR …
=> Fix https://github.com/wso2/product-ei/issues/1882

components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/store/HumanTaskStore.java
This method is unused and public. Therefore remving the method.
The class (if there are any) which extends this method can modify the default folder location …
=> Remove unused setter method

components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/ProcessInstanceService.java
JAXB unmarshalling is not capable of preventing XXE attacks.
Therefore XMLInputFactory is used with XXE prevetions flags
before the actual unmarshalling.
> Brief description of the new feature or bug fix as it will …
=>  Add fix for XXE vulnerability

components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/ExecutionService.java
JAXB unmarshalling is not capable of preventing XXE attacks. Therefore XMLInputFactory is used with XXE prevetions flags before the actual unmarshalling.
> Brief description of the new feature or bug fix as it will …
=> Fix XXE vulnerability at ExecutionService

components/common/src/main/java/org/wso2/carbon/businessprocesses/common/handler/CarbonContextConfigurator.java
Resolve the null pointer exception when initiating a bpel process from jms transport.
> automatically populate carboncontext data for threads which does not have carbon context populated
> added axis2 handler class to populate carbon context
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), …
=> Fix https://github.com/wso2/product-ei/issues/1911

components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/base/BaseExecutionService.java
JAXB unmarshalling is not capable of preventing XXE attacks. Therefore XMLInputFactory is used with XXE prevetions flags before the actual unmarshalling.
> Brief description of the new feature or bug fix as it will …
=> Fix XXE vulnerability at BaseExecutionService

components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/WorkflowTaskService.java
JAXB unmarshalling is not capable of preventing XXE attacks. Therefore XMLInputFactory is used with XXE prevetions flags before the actual unmarshalling of xml content.
> Brief description of the new feature or bug …
=> Fix XXE vulnerability at WorkflowTaskService

components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/WorkflowTaskService.java
JAXB unmarshalling is not capable of preventing XXE attacks. Therefore XMLInputFactory is used with XXE prevetions flags before the actual unmarshalling of xml content.
> Brief description of the new feature or bug …
=> Fix XXE vulnerability

components/bpmn/bpmn-explorer-web/src/web/config/config.json, components/bpmn/bpmn-explorer-web/src/web/controller/privacyController.jag, components/bpmn/bpmn-explorer-web/src/web/jaggery.conf, components/bpmn/bpmn-explorer-web/src/web/template/cookiePolicyView.jag, components/humantask/humantask-explorer-web/src/web/config/config.json, components/humantask/humantask-explorer-web/src/web/controller/privacyController.jag, components/humantask/humantask-explorer-web/src/web/jaggery.conf, components/humantask/humantask-explorer-web/src/web/template/cookiePolicyView.jag
> To show the product's cookie policy
> Resolves wso2/product-ei#1934
> Added jaggery files to show the cookie policy
>
=> Add cookie policy to bpmn and human task explorers

pom.xml
=> Upgrade kernel/identity versions

pom.xml
Update multi tenancy to stable version for EI-6.2.0 release.
=> Update multi tenancy to stable version

pom.xml
=> Upgrade multi-tenancy version

components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/deployment/BPMNDeployer.java
Resolves BPMN artifacts get undeployed when a file system at the time file system gets (un)mounted in bps server instance.
> …
=> Fix https://github.com/wso2/product-ei/issues/1922

pom.xml
Change orbit.fasterxml.jackson version for databind.
> Link(s) to product documentation that addresses the changes of this PR. …
=> Change orbit.fasterxml.jackson version

components/bpmn/org.wso2.carbon.bpmn.analytics.publisher/pom.xml
Upgrade version for weekly release.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Upgrade version

features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml, features/bpel/org.wso2.carbon.bpel.ui.feature/pom.xml, features/bpel/pom.xml, pom.xml
> Upgrade geronimo-kernel version
=> Upgrade geronimo-kernel version from 2.0.1.wso2v1 to 3.0.1

components/bpmn/org.wso2.carbon.bpmn.extensions/src/main/java/org/wso2/carbon/bpmn/extensions/rest/RESTTask.java
Fix the issue https://github.com/wso2/product-ei/issues/2199
=> [EI-2199] Fix Class cast exception in Rest task

pom.xml
This is to upgrade
joda-time/2.9.4.wso2v1
> Link to the PR for changes to the training content in …
=> Upgrade joda-time version

components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/store/Utils.java, components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/deployment/TenantRepository.java, components/humantask/org.wso2.carbon.humantask.ui/src/main/java/org/wso2/carbon/humantask/ui/fileupload/ArchiveExtractor.java, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/deployment/ArchiveBasedHumanTaskDeploymentUnitBuilder.java
This is to validate  files inside the human task, bpel and bpmn file
> Link to the PR for changes to the training content in …
=> Validate the files inside the human task, bpel and bpmn file

components/bpel/org.wso2.carbon.bpel.ui/src/main/java/org/wso2/carbon/bpel/ui/fileupload/ArchiveExtractor.java, components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/deployment/TenantRepository.java
This is to validate files inside the uploaded bpel file and to avoid consuming the bpmn input stream
> Link to the PR for changes …
=> Validate the files inside the uploaded bpel file

pom.xml
Update dependency versions for the release
=> Update depedency versions

pom.xml
=> Upgrade commons and axis2 transport version

features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml, pom.xml
update dependency library to fix human task issue
=> Update membrane soa dependency

components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/dao/jpa/openjpa/model/provider/LogicalPeopleGroupBasedOrgEntityProvider.java
Fixes: wso2/product-ei#2701
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix for wso2/product-ei/issues/2701

components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/BPELConstants.java, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/BPELServerImpl.java, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/config/BPELServerConfiguration.java, components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xml, components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xsd, pom.xml
[BPS][Intermittent] BPEL process Jobs not resumed after mutiple restart in mesos cluster
https://github.com/wso2/product-ei/issues/2833
=> Fix BPEL process Jobs not resumed issue

features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml
remove groovy jar bundling into human task feature
=> remove groovy jar from humantask feature

pom.xml
https://github.com/wso2/product-is/issues/4652
=> Bump asm version to fix bundle duplication

features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml
Reverts wso2/carbon-business-process#555
=> Revert "remove groovy jar from humantask feature"

components/bpmn/org.wso2.carbon.bpmn.extensions/pom.xml, components/bpmn/org.wso2.carbon.bpmn/pom.xml, features/bpmn/org.wso2.carbon.bpmn.server.feature/pom.xml, pom.xml
https://github.com/wso2/product-ei/issues/2061
=> Upgrade json path version to remove duplicates

features/bpmn/org.wso2.carbon.bpmn.server.feature/pom.xml, pom.xml
=> Upgrade databind version

features/bpmn/org.wso2.carbon.bpmn.server.feature/pom.xml, pom.xml
This PR is to update Jackson dependency version.
=>  Bump dependency versions

features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml, features/bpel/org.wso2.carbon.bpel.ui.feature/pom.xml, features/bpel/pom.xml, features/bpmn/org.wso2.carbon.bpmn.server.feature/pom.xml, features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml, pom.xml
Update asm bundle to asm-all 5.2
=> Update asm component

pom.xml
=> Update version range

components/application-mgt/org.wso2.carbon.application.mgt.bpel/pom.xml
=> Update correct import version 

components/application-mgt/org.wso2.carbon.application.mgt.humantask/pom.xml
=> Update correct import version

pom.xml
=> Upgrade carbon multi tenancy version

components/bpel/org.wso2.carbon.bpel.b4p/src/main/java/org/wso2/carbon/bpel/b4p/coordination/configuration/CoordinationConfiguration.java, components/bpmn/org.wso2.carbon.bpmn.analytics.publisher/src/main/java/org/wso2/carbon/bpmn/analytics/publisher/AnalyticsPublisherConstants.java, components/bpmn/org.wso2.carbon.bpmn.analytics.publisher/src/main/java/org/wso2/carbon/bpmn/analytics/publisher/config/BPSAnalyticsConfiguration.java, components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/utils/SecretVaultValueReader.java, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/HumanTaskConstants.java, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/configuration/HumanTaskServerConfiguration.java, pom.xml
> Add secure vault changes for BPS, Humen task and Analytics profiles.
=> Add secure vault changes for bps, humentask, and analytic

pom.xml
> Update import version range
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Update import version range

service-stubs/bpel/org.wso2.carbon.bpel.stub/pom.xml, service-stubs/humantask/org.wso2.carbon.humantask.stub/pom.xml
=> Fix build for jdk 11 changes

components/bpmn/org.wso2.carbon.bpmn.rest/pom.xml, components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/security/AuthenticationHandler.java, components/bpmn/org.wso2.carbon.bpmn.rest/src/main/webapp/META-INF/webapp-classloading.xml
> Upgrade the CXF version to 3.2.8 and replace the deprecated methods in CXFv3 with the relevant methods.
=> CXF upgrade to version 3.x.x

components/bpel/org.wso2.carbon.bpel.b4p/src/main/java/org/wso2/carbon/bpel/b4p/coordination/configuration/CoordinationConfiguration.java, components/bpmn/org.wso2.carbon.bpmn.analytics.publisher/src/main/java/org/wso2/carbon/bpmn/analytics/publisher/AnalyticsPublisherConstants.java, components/bpmn/org.wso2.carbon.bpmn.analytics.publisher/src/main/java/org/wso2/carbon/bpmn/analytics/publisher/config/BPSAnalyticsConfiguration.java, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/HumanTaskConstants.java, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/configuration/HumanTaskServerConfiguration.java
> Set namespace for secure vault reader
=> Set namespaces for secure vault readers

.gitignore, components/attachment-mgt/org.wso2.carbon.attachment.mgt/pom.xml, components/bpel/org.wso2.carbon.bpel.b4p/pom.xml, components/bpmn/org.wso2.carbon.bpmn.analytics.publisher/pom.xml, components/humantask/org.wso2.carbon.humantask/pom.xml, components/humantask/pom.xml, features/attachment-mgt/org.wso2.carbon.attachment.mgt.server.feature/pom.xml, features/attachment-mgt/org.wso2.carbon.attachment.mgt.server.feature/resources/p2.inf, features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml, features/bpel/org.wso2.carbon.bpel.server.feature/resources/p2.inf, features/bpmn/org.wso2.carbon.bpmn.server.feature/pom.xml, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/p2.inf, features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml, features/humantask/org.wso2.carbon.humantask.server.feature/resources/p2.inf, pom.xml
> Update h2 version and  git ignore to skip the db files
> Link to the PR for changes to the training content in …
=> Update h2 version and  git ignore to skip the db files

features/attachment-mgt/org.wso2.carbon.attachment.mgt.server.feature/resources/conf/bps-datasources.xml, features/attachment-mgt/org.wso2.carbon.attachment.mgt.server.feature/resources/conf/datasources.properties, features/bpel/org.wso2.carbon.bpel.server.feature/resources/conf/bps-datasources.xml, features/bpel/org.wso2.carbon.bpel.server.feature/resources/conf/datasources.properties, features/humantask/org.wso2.carbon.humantask.server.feature/resources/conf/bps-datasources.xml, features/humantask/org.wso2.carbon.humantask.server.feature/resources/conf/datasources.properties
> Update h2 database url
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Update h2 database url

components/attachment-mgt/org.wso2.carbon.attachment.mgt/src/main/java/org/wso2/carbon/attachment/mgt/server/internal/AttachmentServiceComponent.java
> Remove throwing exception in deactivate
=> Remove throwing exception in deactivate

features/application-mgt/org.wso2.carbon.application.mgt.bpel.feature/pom.xml, features/application-mgt/org.wso2.carbon.application.mgt.bpel.server.feature/pom.xml, features/application-mgt/org.wso2.carbon.application.mgt.humantask.feature/pom.xml, features/application-mgt/org.wso2.carbon.application.mgt.humantask.server.feature/pom.xml, features/attachment-mgt/org.wso2.carbon.attachment.mgt.feature/pom.xml, features/attachment-mgt/org.wso2.carbon.attachment.mgt.server.feature/pom.xml, features/attachment-mgt/org.wso2.carbon.attachment.mgt.ui.feature/pom.xml, features/bpel/org.wso2.carbon.bpel.feature/pom.xml, features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml, features/bpel/org.wso2.carbon.bpel.ui.feature/pom.xml, features/bpmn/org.wso2.carbon.bpmn.feature/pom.xml, features/bpmn/org.wso2.carbon.bpmn.server.feature/pom.xml, features/bpmn/org.wso2.carbon.bpmn.ui.feature/pom.xml, features/humantask/org.wso2.carbon.humantask.feature/pom.xml, features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml, features/humantask/org.wso2.carbon.humantask.ui.feature/pom.xml, pom.xml
> Introduce new version property for the feature compatible version
=> Introduce new version property for the feature compatible version

pom.xml
> This PR consists kernel version and dependency versions upgrades according to kernel upgrade.
=> Upgrade kernel and other dependency versions

pom.xml
=> update p2 plugin version

components/application-deployers/org.wso2.carbon.application.deployer.bpel/pom.xml, components/application-deployers/org.wso2.carbon.application.deployer.bpmn/pom.xml, components/application-deployers/org.wso2.carbon.application.deployer.humantask/pom.xml, components/application-mgt/org.wso2.carbon.application.mgt.bpel/pom.xml, components/application-mgt/org.wso2.carbon.application.mgt.humantask/pom.xml, components/attachment-mgt/org.wso2.carbon.attachment.mgt/pom.xml, components/bpel/org.wso2.carbon.bpel.analytics.publisher/pom.xml, components/bpel/org.wso2.carbon.bpel.b4p/pom.xml, components/bpel/org.wso2.carbon.bpel.cluster.notifier/pom.xml, components/bpel/org.wso2.carbon.bpel.deployer/pom.xml, components/bpel/org.wso2.carbon.bpel/pom.xml, components/bpmn/org.wso2.carbon.bpmn.analytics.publisher/pom.xml, components/bpmn/org.wso2.carbon.bpmn/pom.xml, components/common/pom.xml, components/humantask/org.wso2.carbon.humantask.coordination.module/pom.xml, components/humantask/org.wso2.carbon.humantask/pom.xml, pom.xml
Update osgi dependency version range
=> update osgi dependency version range

components/bpmn/org.wso2.carbon.bpmn.rest/pom.xml
Remove icu4j dependency due to tomcat incompatibility of icu4j dependency
=> remove icu4j dependency

pom.xml
> This PR will update the dependency versions related to kernel change.
=> Update the dependency versions related to kernel change

pom.xml
> This PR will update dependency versions regarding to kernal upgrade
=> Update dependency versions regarding to kernal upgrade

features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.db2.upgradestep.52100.to.52200.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.db2.upgradestep.52200.to.52300.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.h2.upgradestep.52100.to.52200.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.h2.upgradestep.52200.to.52300.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.hsql.upgradestep.52100.to.52200.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.hsql.upgradestep.52200.to.52300.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.mssql.upgradestep.52100.to.52200.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.mssql.upgradestep.52200.to.52300.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.mysql.upgradestep.52100.to.52200.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.mysql.upgradestep.52200.to.52300.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.mysql55.upgradestep.52100.to.52200.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.mysql55.upgradestep.52200.to.52300.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.oracle.upgradestep.52100.to.52200.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.oracle.upgradestep.52200.to.52300.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.postgres.upgradestep.52100.to.52200.engine.sql, features/bpmn/org.wso2.carbon.bpmn.server.feature/resources/dbscripts/upgrade/activiti.postgres.upgradestep.52200.to.52300.engine.sql, pom.xml
> This PR will upgrade activiti version.
=> Upgrade activiti version to 5.23.0

pom.xml
> This PR will upgrade dependency versions for kernel upgrade.
=> Upgrade dependency versions for kernel upgrade

components/bpmn/org.wso2.carbon.bpmn.extensions/src/main/java/org/wso2/carbon/bpmn/extensions/rest/RESTTask.java, components/bpmn/org.wso2.carbon.bpmn.extensions/src/main/java/org/wso2/carbon/bpmn/extensions/soap/SOAPTask.java
> This pr will add the error handling improvements suggests in the issue: https://github.com/wso2/product-ei/issues/4573 .
=> Add BPMN error handling improvements

pom.xml
Update carbon commons versions
=> Update carbon commons versions

pom.xml
=> Upgrade carbon kernel version range

features/attachment-mgt/org.wso2.carbon.attachment.mgt.feature/pom.xml
=> Change compatible carbon kernel feature version range

components/bpmn/bpmn-explorer-web/src/web/jaggery.conf, components/humantask/humantask-explorer-web/src/web/jaggery.conf
for bpmn-explorer and humantask-explorer
=> Fix Jaggery issue in JDK11

pom.xml
Bump the version of spring.framework to 3.2.9.wso2v2
=> Bump spring framework version

pom.xml
Resolves: https://github.com/wso2/product-is/issues/9369
=> Update Apache groovy version to 2.4.8

components/humantask/org.wso2.carbon.humantask/pom.xml, components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/api/client/TaskOperationsImpl.java
Resolves https://github.com/wso2/product-is/issues/10022
=> Add explicit tenant loading

components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/WorkflowTaskService.java
=> Fix ClassCastException occur with OpenJDK 11

features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml, features/bpel/pom.xml, pom.xml
Reverts wso2/carbon-business-process#625
=> Revert "Remove spring 3 framework."

components/bpmn/org.wso2.carbon.bpmn.rest/src/main/java/org/wso2/carbon/bpmn/rest/service/runtime/WorkflowTaskService.java, components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/MailEventListener.java, components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/internal/BPMNServiceComponent.java
> Add activiti event listener to detect mail tasks, and change the class
loader before the mail task executes.
Fixes wso2/product-ei/issues/5479
=> Change the class loader before Activiti mail tasks

pom.xml
Depends on https://github.com/wso2/orbit/pull/480
Related to https://github.com/wso2/product-is/issues/12479
=> Update com.predic8.soa-model-core version

pom.xml
Related Issues: wso2/product-is#12485
> Update groovy-all version 2.4.8 -> 2.4.21
=> Update groovy-all version

components/humantask/org.wso2.carbon.humantask/pom.xml, features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml, features/bpel/pom.xml, features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml, pom.xml
=> Upgrade Spring and switch to orbit based Groovy

pom.xml
=> Bump orbit.ode version from 1.3.5-wso2v21 to 1.3.5-wso2v22

pom.xml
=> Bump orbit.ode version from 1.3.5-wso2v22 to 1.3.5-wso2v24

pom.xml
=> Bump orbit.ode version from 1.3.5-wso2v24 to 1.3.5-wso2v25

pom.xml
=> update xstream to 1.4.19

components/bpel/org.wso2.carbon.bpel/pom.xml, components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/BPELServerImpl.java, pom.xml
$subject
- Resolves https://github.com/wso2/product-is/issues/13647
=> Upgrade Hazelcast from 3.12.x to 4.2.x

pom.xml
=> Bump orbit.ode version from 1.3.5-wso2v25 to 1.3.5-wso2v26

pom.xml
=> Upgrade Commons Fileupload version

pom.xml
=> Upgrade BCEL to 6.7.0.wso2v1

pom.xml
> Bump com.thoughtworks.xstream:xstream version to mitigate known vulnerabilities.
=> Bump xstream version

pom.xml
$subject
Depends on https://github.com/wso2/orbit/pull/1012
- https://github.com/wso2/product-is/issues/16628
> Link to the PR …
=> Upgrade to hazelcast 5.3.2

components/bpel/org.wso2.carbon.bpel.deployer/src/main/java/org/wso2/carbon/bpel/deployer/services/BPELUploader.java
- $Subject
- filename : ""
- filename : " "
- filename : "../../repository/deployment/server/webapps/accountrecoveryendpoint/shell1.txt"
=> Add filename validation for arbitrary file upload via SOAP admin service
