- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/internal/BPELServiceComponent.java
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/BPELSchedulerShutDown.java
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/BPELServerImpl.java
Registering WaitBeforeShutdownObserver service to shutdown ode scheduler first and taking ode scheduler to the top in the BPELServerImpl.shutdown() method. Resolves the issue -https://wso2.org/jira/browse/BPS-470.
> Changing BPS shutdown order to shut down ode scheduler first

- components/humantask/humantask-explorer-web/src/web/template/inboxView.jag
Removing status column from human task explorer inbox for issue - https://wso2.org/jira/browse/BPS-633.
> Removing status column from human task explorer inbox

- components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/engine/util/CommonTaskUtil.java
Changing human task priority range from 1-10 to 0-10 for issue - https://wso2.org/jira/browse/BPS-515.
> Changing human task priority range from 1-10 to 0-10

- components/bpel/org.wso2.carbon.bpel.ui/src/main/java/org/wso2/carbon/bpel/ui/BpelUIUtil.java
- components/bpel/org.wso2.carbon.bpel.ui/src/main/java/org/wso2/carbon/bpel/ui/clients/InstanceManagementServiceClient.java
- components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/web/bpel/instance_view.jsp
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/BPELConstants.java
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/config/BPELServerConfiguration.java
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/mgt/services/InstanceManagementServiceSkeleton.java
- components/bpel/org.wso2.carbon.bpel/src/main/resources/META-INF/bps_management.xsd
- components/bpel/org.wso2.carbon.bpel/src/main/resources/META-INF/instance_mgt.wsdl
- components/bpel/org.wso2.carbon.bpel/src/main/resources/META-INF/services.xml
- components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xml
- components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xsd
- components/bpel/org.wso2.carbon.bpel/src/test/resources/conf/bps.xml
- features/bpel/org.wso2.carbon.bpel.server.feature/resources/conf/bps.xml
- service-stubs/bpel/org.wso2.carbon.bpel.skeleton/src/main/resources/bps_management.xsd
- service-stubs/bpel/org.wso2.carbon.bpel.skeleton/src/main/resources/instance_mgt.wsdl
- service-stubs/bpel/org.wso2.carbon.bpel.stub/src/main/resources/bps_management.xsd
- service-stubs/bpel/org.wso2.carbon.bpel.stub/src/main/resources/instance_mgt.wsdl
Adding new configuration item to max BPEL instance variable size forUI, truncating variable view in instance view. for issue - https://wso2.org/jira/browse/BPS-597
> Truncating long variables in instance view

- components/bpel/org.wso2.carbon.bpel.ui/src/main/java/org/wso2/carbon/bpel/ui/clients/InstanceManagementServiceClient.java
- components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/org/wso2/carbon/bpel/ui/i18n/Resources.properties
- components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/web/bpel/list_instances.jsp
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/BPELConstants.java
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/config/BPELServerConfiguration.java
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/mgt/services/InstanceManagementServiceSkeleton.java
- components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xml
- components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xsd
- components/bpel/org.wso2.carbon.bpel/src/test/resources/conf/bps.xml
- features/bpel/org.wso2.carbon.bpel.server.feature/resources/conf/bps.xml
Limiting number of bpel instances that can be deleted in single request, to a configuratin value. Issue - https://wso2.org/jira/browse/BPS-228
> Limiting number of bpel instances that can be deleted in single request

- components/humantask/humantask-explorer-web/src/web/css/style.css
In humantask- explorer if the user name is too lengthy, the logout link is not displayed.
> Fixing UI defect of humantask-explorer login name

- service-stubs/bpmn/org.wso2.carbon.bpmn.stub/src/main/resources/BPMNDeploymentService.wsdl
- service-stubs/bpmn/org.wso2.carbon.bpmn.stub/src/main/resources/BPMNHumanTaskService.wsdl
- service-stubs/bpmn/org.wso2.carbon.bpmn.stub/src/main/resources/BPMNInstanceService.wsdl
changing Exception names to avoid inappropriate exception class names. Issue - https://wso2.org/jira/browse/BPS-577
> changing Exception names to avoid inappropriate exception class names

- components/humantask/humantask-explorer-web/src/web/template/taskInstanceView.jag
https://wso2.org/jira/browse/BPS-721 
Workspace elements (drop downs, check boxes, text areas etc.) in task view should disable (or make read-only) for tasks in Completed state
> Fix:https://wso2.org/jira/browse/BPS-721 and some code formatting

- components/bpmn/org.wso2.carbon.bpmn.ui/src/main/resources/web/bpmn/package_dashboard.jsp
When having <href=javascript:deletePackage();"/> in firefox (windows environment) the value returned from the function is set as a string and is rendered. This is fixed by having the javascript function 'onclick'
> Fixing bpmn undeploy issue in firefox

- components/bpmn/org.wso2.carbon.bpmn.extensions/src/main/java/org/wso2/carbon/bpmn/extensions/rest/RESTInvoker.java
- components/bpmn/org.wso2.carbon.bpmn.rest/pom.xml
An input payload that consists of Unicode characters in RESTTask (bpmn) are not handled properly(In both POST and PUT). Related git issue #924.
Also contains  fix for git issue #718.
> [EI-924]Fix unicode character issue in bpmn RESTTask input

- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/BPELSchedulerInitializer.java
Fix to resume execution of process instance (which were running within a loop) after a restart. After a restart of WSO2 BPS server (which may include few minutes break), process instances that were ACTIVE at the time get frozen, meaning their status is ACTIVE, but their execution does not progress anymore.
**Note:** User have to set Node ID in bps.xml
Fix JIRA: https://wso2.org/jira/browse/BPS-1173
> [BPS-1173] Fix:Resuming BPS process instances after server reboot

- components/bpel/org.wso2.carbon.bpel.ui/src/main/resources/web/bpel/process_list.jsp
Fixed broken BPEL process pagination links in bpel process list page (process_list.jsp). The process list filters were not URL encoded hence the above issue occurred in pagination links.
> [EI-1055]Fix broken BPEL Process Navigation Links 

- components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/store/NotificationConfiguration.java
- components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/store/TaskConfiguration.java
- components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/utils/HumanTaskStoreUtils.java
- components/humantask/org.wso2.carbon.humantask/src/main/resources/schemas/hi-config.xsd
> Fix wso2/product-ei/issues/1611
> This fix enables BPS human-tasks to point to a service xml file to pick only necessary transports rather than taking default transports from axis2.xml file.
> Introduce parameter serviceDescriptionReference for BPS human-tasks which was already working for BPEL
> JDK 8, Ubuntu 16.04
> Fix wso2/product-ei/issues/1611

- pom.xml
Upgraded axis2 and axis2-transports to 1.6.1-wso2v23 and 2.0.0.wso2v12 respectively.
> Upgrade axis2 and axis2-transports

- components/bpmn/org.wso2.carbon.bpmn.extensions/src/main/java/org/wso2/carbon/bpmn/extensions/rest/RESTTask.java
> Fixes: https://wso2.org/jira/browse/BPS-1177
> Change the varible setting into global rather than setting them loacal.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Fix https://wso2.org/jira/browse/BPS-1177

- components/bpmn/bpmn-explorer-web/src/web/config/config.json
- components/bpmn/bpmn-explorer-web/src/web/config/locales/locale_en.json
- components/bpmn/bpmn-explorer-web/src/web/model/loginModel.jag
- components/bpmn/bpmn-explorer-web/src/web/template/loginView.jag
- components/humantask/humantask-explorer-web/src/web/config/config.json
- components/humantask/humantask-explorer-web/src/web/config/locales/locale_en.json
- components/humantask/humantask-explorer-web/src/web/model/loginModel.jag
- components/humantask/humantask-explorer-web/src/web/template/loginView.jag
> The purpose of this change to introduce a cookie consent to Human-Task and BPMN explorer login pages in order to comply with GDPR
> Added a banner to notify users about the cookie policy of the organization. It is added as in a configurable manner where admin can either enable/disable the banner by changing the property provided in config.json.
> Add cookie consent to BPMN/Human-task explorers

- components/bpel/org.wso2.carbon.bpel/pom.xml
- pom.xml
The Geronimo framework mandates these dependencies to be visible in OSGI runtime.
The eventual proper solution should be to take geronimo-kernel 3.0.1 into WSO2 orbit as an osgi bundle and then expose these dependencies from there instead of the BPEL profile.
> Expose internal dependencies for geronimo 3.0.1 through bpel component.

- components/bpmn/org.wso2.carbon.bpmn/pom.xml
> Fixes wso2/product-ei/issues/2885
> Resolve conflicts 
> Changed jsonpath import version to resolve conflicts happened as the result of introducing latest jsonpath library (2.4.0) to synapse.
> Change jayway jsonpath import version.

- components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/ActivitiEngineBuilder.java
- components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/BPMNConstants.java
- components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/utils/SecretVaultValueReader.java
- Added SecretVaultValueReader class to convert properties with
secretAlias attributes to the corresponding password stored in the
Secure Vault
- If secretAlias attributes exist, the file is decrypted and converted
to an InputStream. Otherwise, the file is passed as a FileInputStream.
Resolves : https://github.com/wso2/product-ei/issues/3246
> Fix to enable Secure vault for the properties defined within the activity.xml

- features/bpmn/org.wso2.carbon.bpmn.server.feature/pom.xml
- pom.xml
Upgraded json-smart to version 2.3 and packed its transitive dependencies.
> Upgrade json smart version

- components/bpmn/org.wso2.carbon.bpmn.extensions/src/main/java/org/wso2/carbon/bpmn/extensions/rest/RESTTask.java
> This PR will enable the ability to retrieve the error details(status, error description) from the bpmn execution flow so that the user can take the decisions according to that
> Add functionality for errordetails registration for bpmn execution flow

- components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/api/client/TaskOperationsImpl.java
- components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/dao/sql/HumanTaskJPQLQueryBuilder.java
- components/humantask/org.wso2.carbon.humantask/src/main/java/org/wso2/carbon/humantask/core/engine/util/OperationAuthorizationUtil.java
Fix the issue with case insensitive user names when a user logged into Admin portal with case insensitive username
When a user who has the role privileges to perform subscription approval in BPS human tasks tries to log to the EI console with a username with different cases from the original user name created in BPS, subscription approval fails.
Fixes the issue https://github.com/wso2/product-ei/issues/2263
> Fix the issue with case insensitive user names

- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/BPELConstants.java
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/config/BPELServerConfiguration.java
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/store/TenantProcessStoreImpl.java
- components/bpel/org.wso2.carbon.bpel/src/main/resources/schemas/bps.xsd
Fixes the issue thrown when a bpel process is deployed in a slave node
prior to the master node by introducing the BpelDeploy property
where a timeout can be defined to check whether the process is
deployed in master node.
Fixes https://github.com/wso2/product-ei/issues/3998##
> Fixes the issue Error in worker nodes when deploying BPEL process

- components/common/src/main/java/org/wso2/carbon/bpel/common/internal/BPELCommonServiceComponent.java
> Fix Nullpointer exception when shutting down the IS server.
```
ERROR {org.wso2.carbon.bpel.common} - [SCR] Error while attempting to deactivate instance of component Component[
name = org.wso2.carbon.bpel.common.internal.BPELCommonServiceComponent
factory = null
autoenable = true
immediate = true
implementation = org.wso2.carbon.bpel.common.internal.BPELCommonServiceComponent
state = Unsatisfied
properties =
serviceFactory = false
serviceInterface = null
references = {
Reference[name = registry.service, interface = org.wso2.carbon.registry.core.service.RegistryService, policy = dynamic, cardinality = 1..1, target = null, bind = setRegistryService, unbind = unsetRegistryService]
}
located in bundle = org.wso2.carbon.bpel.common_4.5.9 [193]
]
```
> Fix Nullpointer exception when shutting down the IS server.

- components/bpmn/org.wso2.carbon.bpmn.extensions/src/main/java/org/wso2/carbon/bpmn/extensions/rest/RESTTask.java
- components/bpmn/org.wso2.carbon.bpmn/src/main/java/org/wso2/carbon/bpmn/core/types/datatypes/json/api/JsonNodeObject.java
> This PR will introduce a default variable to set for the rest task output mappings if any error response sent from the BE. In the following example if an error response is sent from the backend, then the json path evaluation fails hence it will set the value from the defaultVar for the status.
```xml
<activiti:field name="outputMappings">
<activiti:string>status:$.status:defaultVar</activiti:string>
</activiti:field>
```
Fixes :https://github.com/wso2/product-ei/issues/4573
> Add default variable support for rest task for error handling

- components/bpel/org.wso2.carbon.bpel.ui/pom.xml
- components/bpel/org.wso2.carbon.bpel/pom.xml
- components/bpel/org.wso2.carbon.bpel/src/main/java/org/wso2/carbon/bpel/core/ode/integration/mgt/services/ProcessManagementServiceSkeleton.java
- features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml
- features/bpel/org.wso2.carbon.bpel.ui.feature/pom.xml
- features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml
To get rid of org.wso2.carbon.service.mgt and org.wso2.carbon.module.mgt components from Identity Server distribution we had to do below changes[1] in the carbon-business-process[2]:
- The class ProcessManagementServiceSkeleton[3] was using class[4] from org.wso2.carbon.service.mgt[5] module of carbon-deployment[6] so we copied the required util methods into that class itself and removed the dependency for org.wso2.carbon.service.mgt component.
-  Moved the importFeatureDef for org.wso2.carbon.service.mgt.server from org.wso2.carbon.bpel.server.feature[7] to org.wso2.carbon.bpel.ui.feature[8].
- Removed the importFeatureDef for org.wso2.carbon.service.mgt.server from org.wso2.carbon.humantask.server.feature[9] since it only has imports for ui and stubs and does not have imports for …
> Remove dependency org.wso2.carbon.service.mgt from org.wso2.carbon.bpel module

- components/bpel/org.wso2.carbon.bpel.ui/src/main/java/org/wso2/carbon/bpel/ui/bpel2svg/impl/ActivityImpl.java
- pom.xml
This is to fix wso2/product-ei#5150
The Apache Batik version is upgraded to 1.9.1
> Fix EI-5150 BPEL Process Visualization is not loading with OpenJDK 8

- features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml
- features/bpel/pom.xml
- pom.xml
The spring framework should not be available in the OSGi runtime. It is available in the lib/runtimes and added to the web applications.
> Remove spring 3 framework.

- features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml
- features/bpel/pom.xml
- pom.xml
The spring framework should not be available in the OSGi runtime. It is available in the lib/runtimes and added as an embedded dependency for ode
> Remove spring 3 framework from OSGi

- features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml
- features/bpel/org.wso2.carbon.bpel.ui.feature/pom.xml
- features/bpel/pom.xml
- features/bpmn/org.wso2.carbon.bpmn.server.feature/pom.xml
- features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml
- pom.xml
Update third party dependencies
Related to https://github.com/wso2/product-is/issues/12479
When we update asm library we need to add asm-commons, asm-tree as seperate dependencies since latest asm doesn't contain these packages inside asm.
> Update third party dependencies

- components/attachment-mgt/org.wso2.carbon.attachment.mgt/pom.xml
- components/attachment-mgt/org.wso2.carbon.attachment.mgt/src/test/resources/carbon.xml
- components/bpel/org.wso2.carbon.bpel.b4p/pom.xml
- components/bpmn/org.wso2.carbon.bpmn.analytics.publisher/pom.xml
- components/humantask/org.wso2.carbon.humantask/pom.xml
- components/humantask/pom.xml
- features/attachment-mgt/org.wso2.carbon.attachment.mgt.server.feature/pom.xml
- features/attachment-mgt/org.wso2.carbon.attachment.mgt.server.feature/resources/conf/bps-datasources.xml
- features/attachment-mgt/org.wso2.carbon.attachment.mgt.server.feature/resources/conf/datasources.properties
- features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml
- features/bpel/org.wso2.carbon.bpel.server.feature/resources/conf/bps-datasources.xml
- features/bpel/org.wso2.carbon.bpel.server.feature/resources/conf/datasources.properties
- features/bpmn/org.wso2.carbon.bpmn.server.feature/pom.xml
- features/humantask/org.wso2.carbon.humantask.server.feature/pom.xml
- features/humantask/org.wso2.carbon.humantask.server.feature/resources/conf/bps-datasources.xml
- features/humantask/org.wso2.carbon.humantask.server.feature/resources/conf/datasources.properties
- features/humantask/org.wso2.carbon.humantask.server.feature/resources/conf/org.wso2.carbon.humantask.server.feature.default.json
- pom.xml
This PR: 
- Upgrades the H2 db version from 1.4.199 to 2.1.210
- Removes the MVCC configuration for compatibility with the new H2 version
- Removes the H2 console
Related to: https://github.com/wso2/product-is/issues/13162
> Upgrade H2 DB version and Remove H2 Console

- features/bpel/org.wso2.carbon.bpel.server.feature/pom.xml
- features/bpel/org.wso2.carbon.bpel.ui.feature/pom.xml
- features/bpel/pom.xml
- pom.xml
The orbit based geronimo-kernel bundle does not require xstream 1.3 library. The need for this arise after the xstream version update. https://github.com/wso2/carbon-business-process/pull/664
Resolves - https://github.com/wso2/product-is/issues/13598
> Change Geronimo kernel to use orbit bundle

- pom.xml
Upgrade the `org.wso2.orbit.com.h2database:h2-engine` to 2.2.220.wso2v1
Merge after https://github.com/wso2/orbit/pull/994 is merged and released
> Update h2-engine dependency version
